DROP DATABASE IF EXISTS `DB_AUTOLOG`;
CREATE DATABASE `DB_AUTOLOG`
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE `DB_AUTOLOG`;

CREATE TABLE `USER_AUTOLOG` (
  `IDUSER_USA` INT NOT NULL AUTO_INCREMENT COMMENT 'Clave primaria',
  `USERNAME_USA` VARCHAR(50) NOT NULL COMMENT 'Nombre de usuario',
  `EMAIL_USA` VARCHAR(100) NOT NULL COMMENT 'Correo electrónico',
  `PASSWORD_USA` VARCHAR(255) NOT NULL COMMENT 'Contraseña cifrada',
  `S_ACTIVEROW_USA` TINYINT(1) NOT NULL DEFAULT 1 COMMENT 'Registro activo',
  `S_INSERTDATE_USA` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha de inserción',
  `S_UPDATEDATE_USA` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Fecha de última actualización',
  PRIMARY KEY (`IDUSER_USA`),
  UNIQUE KEY `UK_USER_USERNAME` (`USERNAME_USA`),
  UNIQUE KEY `UK_USER_EMAIL` (`EMAIL_USA`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `ROL_AUTOLOG` (
  `IDROL_ROA` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador del rol',
  `ROLCODE_ROA` VARCHAR(50) NOT NULL COMMENT 'Código del rol',
  `ROLNAME_ROA` VARCHAR(100) NOT NULL COMMENT 'Nombre del rol',
  `S_ACTIVEROW_ROA` TINYINT(1) NOT NULL DEFAULT 1 COMMENT 'Registro activo',
  `S_INSERTDATE_ROA` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha de inserción',
  `S_UPDATEDATE_ROA` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Fecha de última actualización',
  PRIMARY KEY (`IDROL_ROA`),
  UNIQUE KEY `UK_ROL_CODE` (`ROLCODE_ROA`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `USERROL_AUTOLOG` (
  `IDUSER_URA` INT NOT NULL COMMENT 'Usuario',
  `IDROL_URA` INT NOT NULL COMMENT 'Rol',
  PRIMARY KEY (`IDUSER_URA`, `IDROL_URA`),
  CONSTRAINT `FK_USERROL_USER`
    FOREIGN KEY (`IDUSER_URA`)
    REFERENCES `USER_AUTOLOG` (`IDUSER_USA`),
  CONSTRAINT `FK_USERROL_ROL`
    FOREIGN KEY (`IDROL_URA`)
    REFERENCES `ROL_AUTOLOG` (`IDROL_ROA`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `VEHICLE_AUTOLOG` (
  `IDVEHICLE_VEA` INT NOT NULL AUTO_INCREMENT COMMENT 'Clave primaria',
  `TYPE_VEA` ENUM('COCHE','FURGON','MOTO','CAMION') NOT NULL,
  `BRAND_VEA` VARCHAR(50) NOT NULL COMMENT 'Marca',
  `MODEL_VEA` VARCHAR(50) NOT NULL COMMENT 'Modelo',
  `PLATE_VEA` VARCHAR(9) NOT NULL COMMENT 'Matrícula' 
    CHECK (
      PLATE_VEA REGEXP '^[A-Z]{1,2}[0-9]{1,5}[A-Z]{1,2}$' OR
      PLATE_VEA REGEXP '^[0-9]{4}[BCDFGHJKLMNPRSTVWXYZ]{3}$'
    ),
  `REGISTRATIONDATE_VEA` DATE,
  `IDUSER_VEA` INT NOT NULL COMMENT 'Propietario',
  `S_ACTIVEROW_VEA` TINYINT(1) NOT NULL DEFAULT 1 COMMENT 'Registro activo',
  `S_INSERTDATE_VEA` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha de inserción',
  `S_UPDATEDATE_VEA` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Fecha de última actualización',
  PRIMARY KEY (`IDVEHICLE_VEA`),
  UNIQUE KEY `UK_VEHICLE_PLATE` (`PLATE_VEA`),
  CONSTRAINT `FK_VEHICLE_USER`
    FOREIGN KEY (`IDUSER_VEA`)
    REFERENCES `USER_AUTOLOG` (`IDUSER_USA`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `OPERATION_AUTOLOG` (
  `IDOPERATION_OPE` INT NOT NULL AUTO_INCREMENT COMMENT 'Clave primaria',
  `TYPE_OPE` ENUM('MANTENIMIENTO','REPARACION','INSPECCION') NOT NULL,
  `DATE_OPE` DATE NOT NULL,
  `COST_OPE` DECIMAL(10,2),
  `PLACE_OPE` VARCHAR(50) NOT NULL COMMENT 'Lugar',
  `DESCRIPTION_OPE` TEXT,
  `IDVEHICLE_OPE` INT NOT NULL,
  `S_ACTIVEROW_OPE` TINYINT(1) NOT NULL DEFAULT 1 COMMENT 'Registro activo',
  `S_INSERTDATE_OPE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha de inserción',
  `S_UPDATEDATE_OPE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Fecha de última actualización',
  PRIMARY KEY (`IDOPERATION_OPE`),
  CONSTRAINT `FK_OPERATION_VEHICLE`
    FOREIGN KEY (`IDVEHICLE_OPE`)
    REFERENCES `VEHICLE_AUTOLOG` (`IDVEHICLE_VEA`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `DOCUMENT_AUTOLOG` (
  `IDDOCUMENT_DOA` INT NOT NULL AUTO_INCREMENT COMMENT 'Clave primaria',
  `FILENAME_DOA` VARCHAR(150) NOT NULL,
  `FILEPATH_DOA` VARCHAR(255) NOT NULL,
  `TYPE_DOA` VARCHAR(50),
  `IDOPERATION_DOA` INT NOT NULL,
  `S_ACTIVEROW_DOA` TINYINT(1) NOT NULL DEFAULT 1 COMMENT 'Registro activo',
  `S_INSERTDATE_DOA` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha de inserción',
  `S_UPDATEDATE_DOA` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Fecha de última actualización',
  PRIMARY KEY (`IDDOCUMENT_DOA`),
  CONSTRAINT `FK_DOCUMENT_OPERATION`
    FOREIGN KEY (`IDOPERATION_DOA`)
    REFERENCES `OPERATION_AUTOLOG` (`IDOPERATION_OPE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `db_autolog`.`userrol_autolog` (`IDUSER_URA`, `IDROL_URA`) VALUES ('1', '1');
INSERT INTO `db_autolog`.`userrol_autolog` (`IDUSER_URA`, `IDROL_URA`) VALUES ('2', '3');
INSERT INTO `db_autolog`.`userrol_autolog` (`IDUSER_URA`, `IDROL_URA`) VALUES ('3', '3');
INSERT INTO `db_autolog`.`userrol_autolog` (`IDUSER_URA`, `IDROL_URA`) VALUES ('3', '4');

INSERT INTO `db_autolog`.`user_autolog` (`USERNAME_USA`, `EMAIL_USA`, `PASSWORD_USA`) VALUES ('usuario1', 'usuario1@test.com', '$2a$10$cvS4CSwDVvKH.YAKWWO0KePkNSf7LIWxGwSGKHxd33SAxHhvDligm'); -- pass: Usuario1
INSERT INTO `db_autolog`.`user_autolog` (`USERNAME_USA`, `EMAIL_USA`, `PASSWORD_USA`) VALUES ('usuario2', 'usuario2@test.com', '$2a$10$g4.2bq8AYLIi6.4PfIEyD.QNdVGt8VucEgCq6IsoE5LzOyTenohoW'); -- pass: Usuario2
INSERT INTO `db_autolog`.`user_autolog` (`USERNAME_USA`, `EMAIL_USA`, `PASSWORD_USA`) VALUES ('usuario3', 'usuario3@test.com', '$2a$2a$10$ACiUKOaLhulTmCkx56aTGuOGHjJSl.sYF5eGpbI1DS7a0VyRLacFy'); -- pass: Usuario3

INSERT INTO `db_autolog`.`rol_autolog` (`ROLCODE_ROA`, `ROLNAME_ROA`) VALUES ('admin', 'administrador');
INSERT INTO `db_autolog`.`rol_autolog` (`ROLCODE_ROA`, `ROLNAME_ROA`) VALUES ('basic', 'basico');
INSERT INTO `db_autolog`.`rol_autolog` (`ROLCODE_ROA`, `ROLNAME_ROA`) VALUES ('lectura', 'lectura');
INSERT INTO `db_autolog`.`rol_autolog` (`ROLCODE_ROA`, `ROLNAME_ROA`) VALUES ('escritura', 'escritura');

